[package]
name = "_origrun"
version = "0.1.0"
authors = ["wordi <wordijp@gmail.com>"]

[dependencies]
regex = "1"
crossbeam-channel = "0.3"
ctrlc = { version = "3.0", features = ["termination"] }

encoding_rs = "0.8"
memchr = { version = "2", default-features = false }
